# Generated by Django 6.0.3 on 2026-03-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_cargo_titulo_profile_hoja_de_vida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('calificacion', models.IntegerField(default=5)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.profile')),
            ],
        ),
    ]
