# Generated by Django 6.0.3 on 2026-03-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empresa_capacidad_empleados',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='empresa_direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='empresa_logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas_logos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='empresa_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='empresa_ruc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='empresa_sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
