# Generated by Django 6.0.3 on 2026-03-25 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_empresa_capacidad_empleados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('modalidad', models.CharField(choices=[('remoto', 'Remoto'), ('hibrido', 'Híbrido'), ('presencial', 'Presencial')], default='presencial', max_length=50)),
                ('tipo_contrato', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('freelance', 'Freelance/Contrato'), ('pasantia', 'Pasantía/Prácticas')], default='tiempo_completo', max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('estado', models.BooleanField(default=True, verbose_name='Oferta Activa')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.profile')),
            ],
        ),
    ]
