# Generated by Django 6.0.3 on 2026-03-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='sueldo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sueldo (opcional)'),
        ),
    ]
