# Generated by Django 6.0.3 on 2026-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_oferta_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empresa_mapa_url',
            field=models.URLField(blank=True, verbose_name='Enlace de Google Maps'),
        ),
    ]
