# Generated by Django 6.0.3 on 2026-03-26 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_empresa_mapa_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Por Clasificar / Sin Revisar'), ('entrevista_pendiente', 'Entrevista Pendiente'), ('entrevistado', 'Entrevistado'), ('cumple', 'Cumple Requisitos'), ('no_cumple', 'No Cumple Requisitos')], default='pendiente', max_length=30)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_hechas', to='core.profile')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_clasificaciones', to='core.profile')),
            ],
            options={
                'unique_together': {('empresa', 'postulante')},
            },
        ),
    ]
