# Generated by Django 6.0.3 on 2026-03-26 22:00

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_postulacion'),
    ]

    operations = [
        UnaccentExtension(),
    ]
