# Generated by Django 6.0.3 on 2026-04-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='etiqueta',
            field=models.CharField(choices=[('tecnologia', 'Tecnología e Informática'), ('diseño_web', 'Diseño Web / UI-UX'), ('administracion', 'Administración / Gestión'), ('ventas', 'Ventas y Marketing'), ('contabilidad', 'Contabilidad y Finanzas'), ('educacion', 'Educación / Docencia'), ('salud', 'Salud y Medicina'), ('ingenieria', 'Ingeniería y Construcción'), ('logistica', 'Logística y Transporte'), ('moda', 'Moda y Textil'), ('gastronomia', 'Gastronomía y Turismo'), ('legal', 'Legal y Jurídico'), ('recursos_humanos', 'Recursos Humanos'), ('otro', 'Otro / General')], default='otro', max_length=50, verbose_name='Categoría / Etiqueta'),
        ),
    ]
