# Generated by Django 6.0.3 on 2026-04-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_oferta_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='ubicacion_mapa_url',
            field=models.URLField(blank=True, verbose_name='Enlace Google Maps de la ubicación'),
        ),
    ]
