# Generated by Django 6.0.3 on 2026-04-18 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ofertafoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiere_verificacion_correo', models.BooleanField(default=True, verbose_name='Exigir verificación por correo al registrarse')),
            ],
            options={
                'verbose_name': 'Configuración de la Plataforma',
                'verbose_name_plural': 'Configuración de la Plataforma',
            },
        ),
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_verificacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
