# Generated by Django 6.0.3 on 2026-04-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_codigoverificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requiere_2fa',
            field=models.BooleanField(default=False, verbose_name='Verificación en dos pasos'),
        ),
    ]
