# Generated by Django 6.0.3 on 2026-04-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_profile_preferencias_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='max_postulantes',
            field=models.PositiveIntegerField(blank=True, help_text='Deja en blanco para no tener límite', null=True, verbose_name='Límite máximo de postulantes'),
        ),
    ]
