# Generated by Django 6.0.3 on 2026-04-21 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_oferta_max_postulantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('resultado_kanban', 'Resultado de clasificación'), ('nueva_postulacion', 'Nueva postulación recibida'), ('nueva_resena', 'Nueva reseña recibida')], max_length=30)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='core.oferta')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_postulacion', to='core.profile')),
            ],
            options={
                'verbose_name': 'Bloqueo de Postulación',
                'verbose_name_plural': 'Bloqueos de Postulación',
                'unique_together': {('postulante', 'oferta')},
            },
        ),
    ]
